import { Location } from '../model/location.model';

export const MOCK_LOCATIONS: Location[] = [
  {
    id: '1',
    name: 'FitX München Zentrum',
    street: 'Karlsplatz 12',
    zip: '80335',
    city: 'München',
    country: 'Deutschland',
    phone: '+49 89 1234567',
    email: 'muenchen@fitx.de',
    website: 'https://www.fitx.de',
  },
  {
    id: '2',
    name: 'McFIT Berlin Mitte',
    street: 'Alexanderplatz 5',
    zip: '10178',
    city: 'Berlin',
    country: 'Deutschland',
    phone: '+49 30 9876543',
    email: 'berlin@mcfit.com',
    website: 'https://www.mcfit.com',
  },
  {
    id: '3',
    name: 'Gold\'s Gym Hamburg',
    street: 'Reeperbahn 42',
    zip: '20359',
    city: 'Hamburg',
    country: 'Deutschland',
    phone: '+49 40 5551234',
    email: 'hamburg@goldsgym.de',
    website: 'https://www.goldsgym.de',
  },
  {
    id: '4',
    name: 'Clever Fit Köln',
    street: 'Hohenzollernring 88',
    zip: '50672',
    city: 'Köln',
    country: 'Deutschland',
    phone: '+49 221 4443210',
    email: 'koeln@clever-fit.com',
    website: 'https://www.clever-fit.com',
  },
  {
    id: '5',
    name: 'John Reed Frankfurt',
    street: 'Zeil 15',
    zip: '60313',
    city: 'Frankfurt am Main',
    country: 'Deutschland',
    phone: '+49 69 7778899',
    email: 'frankfurt@johnreed.fitness',
    website: 'https://www.johnreed.fitness',
  },
  {
    id: '6',
    name: 'Urban Sports Club Stuttgart',
    street: 'Königstraße 30',
    zip: '70173',
    city: 'Stuttgart',
    country: 'Deutschland',
    phone: '+49 711 6665544',
    email: 'stuttgart@urbansportsclub.com',
    website: 'https://www.urbansportsclub.com',
  },
  {
    id: '7',
    name: 'CrossFit Box Düsseldorf',
    street: 'Friedrichstraße 7',
    zip: '40217',
    city: 'Düsseldorf',
    country: 'Deutschland',
    phone: '+49 211 3332211',
    email: 'duesseldorf@crossfit.de',
    website: 'https://www.crossfit.de',
  },
  {
    id: '8',
    name: 'Fitness First Nürnberg',
    street: 'Breite Gasse 22',
    zip: '90402',
    city: 'Nürnberg',
    country: 'Deutschland',
    phone: '+49 911 2221100',
    email: 'nuernberg@fitnessfirst.de',
    website: 'https://www.fitnessfirst.de',
  },
  {
    id: '9',
    name: 'FitStar Leipzig',
    street: 'Augustusplatz 3',
    zip: '04109',
    city: 'Leipzig',
    country: 'Deutschland',
    phone: '+49 341 8889900',
    email: 'leipzig@fitstar.de',
    website: 'https://www.fitstar.de',
  },
  {
    id: '10',
    name: 'Bodystreet Dresden',
    street: 'Prager Straße 10',
    zip: '01069',
    city: 'Dresden',
    country: 'Deutschland',
    phone: '+49 351 4445566',
    email: 'dresden@bodystreet.com',
    website: 'https://www.bodystreet.com',
  },
];
