import { Exercise } from '../model/exercise.model';

export const MOCK_EXERCISES: Exercise[] = [
  { id: '1', name: 'Bankdrücken', type: 'strength', muscleGroups: ['chest', 'triceps', 'shoulders'], equipmentIds: ['7'] },
  { id: '2', name: 'Schrägbankdrücken', type: 'strength', muscleGroups: ['chest', 'triceps', 'shoulders'], equipmentIds: ['7'] },
  { id: '3', name: 'Butterfly', type: 'strength', muscleGroups: ['chest'], equipmentIds: ['16'] },
  { id: '4', name: 'Klimmzüge', type: 'strength', muscleGroups: ['back', 'biceps', 'lats'], equipmentIds: ['22'] },
  { id: '5', name: 'Latzug', type: 'strength', muscleGroups: ['back', 'biceps', 'lats'], equipmentIds: ['17'] },
  { id: '6', name: 'Rudern vorgebeugt', type: 'strength', muscleGroups: ['back', 'biceps', 'traps'], equipmentIds: ['7'] },
  { id: '7', name: 'Kreuzheben', type: 'strength', muscleGroups: ['back', 'glutes', 'hamstrings', 'traps'], equipmentIds: ['7'] },
  { id: '8', name: 'Schulterdrücken', type: 'strength', muscleGroups: ['shoulders', 'triceps'], equipmentIds: ['1'] },
  { id: '9', name: 'Seitheben', type: 'strength', muscleGroups: ['shoulders'], equipmentIds: ['1'] },
  { id: '10', name: 'Frontheben', type: 'strength', muscleGroups: ['shoulders'], equipmentIds: ['1'] },
  { id: '11', name: 'Bizeps-Curls', type: 'strength', muscleGroups: ['biceps', 'forearms'], equipmentIds: ['1', '8'] },
  { id: '12', name: 'Hammer-Curls', type: 'strength', muscleGroups: ['biceps', 'forearms'], equipmentIds: ['1'] },
  { id: '13', name: 'Trizeps-Dips', type: 'strength', muscleGroups: ['triceps', 'chest'], equipmentIds: ['23'] },
  { id: '14', name: 'Trizepsdrücken am Kabel', type: 'strength', muscleGroups: ['triceps'], equipmentIds: ['13'] },
  { id: '15', name: 'Kniebeugen', type: 'strength', muscleGroups: ['quadriceps', 'glutes', 'hamstrings'], equipmentIds: ['7'] },
  { id: '16', name: 'Beinpresse', type: 'strength', muscleGroups: ['quadriceps', 'glutes'], equipmentIds: ['15'] },
  { id: '17', name: 'Beinstrecker', type: 'strength', muscleGroups: ['quadriceps'], equipmentIds: [] },
  { id: '18', name: 'Beinbeuger', type: 'strength', muscleGroups: ['hamstrings'], equipmentIds: [] },
  { id: '19', name: 'Wadenheben', type: 'strength', muscleGroups: ['calves'], equipmentIds: [] },
  { id: '20', name: 'Crunches', type: 'strength', muscleGroups: ['abs'], equipmentIds: ['21'] },
  { id: '21', name: 'Plank', type: 'strength', muscleGroups: ['abs', 'shoulders'], equipmentIds: ['21'] },
  { id: '22', name: 'Russian Twist', type: 'strength', muscleGroups: ['abs'], equipmentIds: ['24'] },
  { id: '23', name: 'Hip Thrust', type: 'strength', muscleGroups: ['glutes', 'hamstrings'], equipmentIds: ['7'] },
  { id: '24', name: 'Ausfallschritte', type: 'strength', muscleGroups: ['quadriceps', 'glutes', 'hamstrings'], equipmentIds: ['1'] },
  { id: '25', name: 'Face Pulls', type: 'strength', muscleGroups: ['shoulders', 'traps', 'back'], equipmentIds: ['13'] },
  { id: '26', name: 'Shrugs', type: 'strength', muscleGroups: ['traps'], equipmentIds: ['1'] },
  { id: '27', name: 'Unterarm-Curls', type: 'strength', muscleGroups: ['forearms'], equipmentIds: ['1', '8'] },
  { id: '28', name: 'Hüftbeuger-Stretch', type: 'strength', muscleGroups: ['hip-flexors'], equipmentIds: ['21'] },
  { id: '29', name: 'Laufen', type: 'cardio', muscleGroups: ['quadriceps', 'hamstrings', 'calves', 'glutes'], equipmentIds: [] },
];
