import { Exercise } from '../model/exercise.model';

export const MOCK_EXERCISES: Exercise[] = [
  { id: '1', name: 'Bankdrücken', muscleGroups: ['chest', 'triceps', 'shoulders'] },
  { id: '2', name: 'Schrägbankdrücken', muscleGroups: ['chest', 'triceps', 'shoulders'] },
  { id: '3', name: 'Butterfly', muscleGroups: ['chest'] },
  { id: '4', name: 'Klimmzüge', muscleGroups: ['back', 'biceps', 'lats'] },
  { id: '5', name: 'Latzug', muscleGroups: ['back', 'biceps', 'lats'] },
  { id: '6', name: 'Rudern vorgebeugt', muscleGroups: ['back', 'biceps', 'traps'] },
  { id: '7', name: 'Kreuzheben', muscleGroups: ['back', 'glutes', 'hamstrings', 'traps'] },
  { id: '8', name: 'Schulterdrücken', muscleGroups: ['shoulders', 'triceps'] },
  { id: '9', name: 'Seitheben', muscleGroups: ['shoulders'] },
  { id: '10', name: 'Frontheben', muscleGroups: ['shoulders'] },
  { id: '11', name: 'Bizeps-Curls', muscleGroups: ['biceps', 'forearms'] },
  { id: '12', name: 'Hammer-Curls', muscleGroups: ['biceps', 'forearms'] },
  { id: '13', name: 'Trizeps-Dips', muscleGroups: ['triceps', 'chest'] },
  { id: '14', name: 'Trizepsdrücken am Kabel', muscleGroups: ['triceps'] },
  { id: '15', name: 'Kniebeugen', muscleGroups: ['quadriceps', 'glutes', 'hamstrings'] },
  { id: '16', name: 'Beinpresse', muscleGroups: ['quadriceps', 'glutes'] },
  { id: '17', name: 'Beinstrecker', muscleGroups: ['quadriceps'] },
  { id: '18', name: 'Beinbeuger', muscleGroups: ['hamstrings'] },
  { id: '19', name: 'Wadenheben', muscleGroups: ['calves'] },
  { id: '20', name: 'Crunches', muscleGroups: ['abs'] },
  { id: '21', name: 'Plank', muscleGroups: ['abs', 'shoulders'] },
  { id: '22', name: 'Russian Twist', muscleGroups: ['abs'] },
  { id: '23', name: 'Hip Thrust', muscleGroups: ['glutes', 'hamstrings'] },
  { id: '24', name: 'Ausfallschritte', muscleGroups: ['quadriceps', 'glutes', 'hamstrings'] },
  { id: '25', name: 'Face Pulls', muscleGroups: ['shoulders', 'traps', 'back'] },
  { id: '26', name: 'Shrugs', muscleGroups: ['traps'] },
  { id: '27', name: 'Unterarm-Curls', muscleGroups: ['forearms'] },
  { id: '28', name: 'Hüftbeuger-Stretch', muscleGroups: ['hip-flexors'] },
];
