import { Exercise } from '../model/exercise.model';

export const MOCK_EXERCISES: Exercise[] = [
  { id: '1', name: 'Bankdrücken', muscleGroups: ['chest', 'triceps', 'shoulders'], equipmentIds: ['7'] },
  { id: '2', name: 'Schrägbankdrücken', muscleGroups: ['chest', 'triceps', 'shoulders'], equipmentIds: ['7'] },
  { id: '3', name: 'Butterfly', muscleGroups: ['chest'], equipmentIds: ['16'] },
  { id: '4', name: 'Klimmzüge', muscleGroups: ['back', 'biceps', 'lats'], equipmentIds: ['22'] },
  { id: '5', name: 'Latzug', muscleGroups: ['back', 'biceps', 'lats'], equipmentIds: ['17'] },
  { id: '6', name: 'Rudern vorgebeugt', muscleGroups: ['back', 'biceps', 'traps'], equipmentIds: ['7'] },
  { id: '7', name: 'Kreuzheben', muscleGroups: ['back', 'glutes', 'hamstrings', 'traps'], equipmentIds: ['7'] },
  { id: '8', name: 'Schulterdrücken', muscleGroups: ['shoulders', 'triceps'], equipmentIds: ['1'] },
  { id: '9', name: 'Seitheben', muscleGroups: ['shoulders'], equipmentIds: ['1'] },
  { id: '10', name: 'Frontheben', muscleGroups: ['shoulders'], equipmentIds: ['1'] },
  { id: '11', name: 'Bizeps-Curls', muscleGroups: ['biceps', 'forearms'], equipmentIds: ['1', '8'] },
  { id: '12', name: 'Hammer-Curls', muscleGroups: ['biceps', 'forearms'], equipmentIds: ['1'] },
  { id: '13', name: 'Trizeps-Dips', muscleGroups: ['triceps', 'chest'], equipmentIds: ['23'] },
  { id: '14', name: 'Trizepsdrücken am Kabel', muscleGroups: ['triceps'], equipmentIds: ['13'] },
  { id: '15', name: 'Kniebeugen', muscleGroups: ['quadriceps', 'glutes', 'hamstrings'], equipmentIds: ['7'] },
  { id: '16', name: 'Beinpresse', muscleGroups: ['quadriceps', 'glutes'], equipmentIds: ['15'] },
  { id: '17', name: 'Beinstrecker', muscleGroups: ['quadriceps'], equipmentIds: [] },
  { id: '18', name: 'Beinbeuger', muscleGroups: ['hamstrings'], equipmentIds: [] },
  { id: '19', name: 'Wadenheben', muscleGroups: ['calves'], equipmentIds: [] },
  { id: '20', name: 'Crunches', muscleGroups: ['abs'], equipmentIds: ['21'] },
  { id: '21', name: 'Plank', muscleGroups: ['abs', 'shoulders'], equipmentIds: ['21'] },
  { id: '22', name: 'Russian Twist', muscleGroups: ['abs'], equipmentIds: ['24'] },
  { id: '23', name: 'Hip Thrust', muscleGroups: ['glutes', 'hamstrings'], equipmentIds: ['7'] },
  { id: '24', name: 'Ausfallschritte', muscleGroups: ['quadriceps', 'glutes', 'hamstrings'], equipmentIds: ['1'] },
  { id: '25', name: 'Face Pulls', muscleGroups: ['shoulders', 'traps', 'back'], equipmentIds: ['13'] },
  { id: '26', name: 'Shrugs', muscleGroups: ['traps'], equipmentIds: ['1'] },
  { id: '27', name: 'Unterarm-Curls', muscleGroups: ['forearms'], equipmentIds: ['1', '8'] },
  { id: '28', name: 'Hüftbeuger-Stretch', muscleGroups: ['hip-flexors'], equipmentIds: ['21'] },
];
