import { Equipment } from '../model/equipment.model';

export const MOCK_EQUIPMENT: Equipment[] = [
  { id: '1', name: 'Kurzhantel 5kg', category: 'dumbbell', weight: 5 },
  { id: '2', name: 'Kurzhantel 8kg', category: 'dumbbell', weight: 8 },
  { id: '3', name: 'Kurzhantel 10kg', category: 'dumbbell', weight: 10 },
  { id: '4', name: 'Kurzhantel 12.5kg', category: 'dumbbell', weight: 12.5 },
  { id: '5', name: 'Kurzhantel 15kg', category: 'dumbbell', weight: 15 },
  { id: '6', name: 'Kurzhantel 20kg', category: 'dumbbell', weight: 20 },
  { id: '7', name: 'Langhantel 20kg', category: 'barbell', weight: 20 },
  { id: '8', name: 'SZ-Stange 10kg', category: 'barbell', weight: 10 },
  { id: '9', name: 'Laufband', category: 'cardio', weight: null },
  { id: '10', name: 'Rudergerät', category: 'cardio', weight: null },
  { id: '11', name: 'Fahrrad-Ergometer', category: 'cardio', weight: null },
  { id: '12', name: 'Crosstrainer', category: 'cardio', weight: null },
  { id: '13', name: 'Kabelzug', category: 'cable', weight: null },
  { id: '14', name: 'Kabelturm doppelt', category: 'cable', weight: null },
  { id: '15', name: 'Beinpresse', category: 'machine', weight: null },
  { id: '16', name: 'Brustpresse', category: 'machine', weight: null },
  { id: '17', name: 'Latzugmaschine', category: 'machine', weight: null },
  { id: '18', name: 'Schulterpresse', category: 'machine', weight: null },
  { id: '19', name: 'Faszienrolle', category: 'mobility', weight: null },
  { id: '20', name: 'Widerstandsband', category: 'mobility', weight: null },
  { id: '21', name: 'Yogamatte', category: 'mobility', weight: null },
  { id: '22', name: 'Klimmzugstange', category: 'bodyweight', weight: null },
  { id: '23', name: 'Dip-Station', category: 'bodyweight', weight: null },
  { id: '24', name: 'Kettlebell 12kg', category: 'other', weight: 12 },
  { id: '25', name: 'Kettlebell 16kg', category: 'other', weight: 16 },
];
