import { UserProfile } from '../model/user.model';

export const MOCK_USERS: UserProfile[] = [
  { id: '1', username: 'admin', firstName: 'Max', lastName: 'Mustermann', email: 'max@example.com', role: 'admin', password: 'admin' },
  { id: '2', username: 'jdoe', firstName: 'Jane', lastName: 'Doe', email: 'jane@example.com', role: 'user', password: 'jdoe' },
  { id: '3', username: 'bsmith', firstName: 'Bob', lastName: 'Smith', email: 'bob@example.com', role: 'user', password: 'bsmith' },
  { id: '4', username: 'amueller', firstName: 'Anna', lastName: 'Müller', email: 'anna.mueller@example.com', role: 'user', password: 'amueller' },
  { id: '5', username: 'tweber', firstName: 'Thomas', lastName: 'Weber', email: 'thomas.weber@example.com', role: 'user', password: 'tweber' },
  { id: '6', username: 'lschneider', firstName: 'Laura', lastName: 'Schneider', email: 'laura.schneider@example.com', role: 'admin', password: 'lschneider' },
  { id: '7', username: 'mfischer', firstName: 'Michael', lastName: 'Fischer', email: 'michael.fischer@example.com', role: 'user', password: 'mfischer' },
  { id: '8', username: 'swagner', firstName: 'Sophie', lastName: 'Wagner', email: 'sophie.wagner@example.com', role: 'user', password: 'swagner' },
  { id: '9', username: 'phoffmann', firstName: 'Paul', lastName: 'Hoffmann', email: 'paul.hoffmann@example.com', role: 'user', password: 'phoffmann' },
  { id: '10', username: 'kbauer', firstName: 'Katrin', lastName: 'Bauer', email: 'katrin.bauer@example.com', role: 'user', password: 'kbauer' },
  { id: '11', username: 'jrichter', firstName: 'Jonas', lastName: 'Richter', email: 'jonas.richter@example.com', role: 'admin', password: 'jrichter' },
  { id: '12', username: 'mklein', firstName: 'Maria', lastName: 'Klein', email: 'maria.klein@example.com', role: 'user', password: 'mklein' },
  { id: '13', username: 'dschmidt', firstName: 'Daniel', lastName: 'Schmidt', email: 'daniel.schmidt@example.com', role: 'user', password: 'dschmidt' },
  { id: '14', username: 'lbraun', firstName: 'Lisa', lastName: 'Braun', email: 'lisa.braun@example.com', role: 'user', password: 'lbraun' },
  { id: '15', username: 'fkrause', firstName: 'Felix', lastName: 'Krause', email: 'felix.krause@example.com', role: 'user', password: 'fkrause' },
  { id: '16', username: 'nwolf', firstName: 'Nina', lastName: 'Wolf', email: 'nina.wolf@example.com', role: 'admin', password: 'nwolf' },
  { id: '17', username: 'sschulz', firstName: 'Stefan', lastName: 'Schulz', email: 'stefan.schulz@example.com', role: 'user', password: 'sschulz' },
  { id: '18', username: 'jneumann', firstName: 'Julia', lastName: 'Neumann', email: 'julia.neumann@example.com', role: 'user', password: 'jneumann' },
  { id: '19', username: 'thaas', firstName: 'Tim', lastName: 'Haas', email: 'tim.haas@example.com', role: 'user', password: 'thaas' },
  { id: '20', username: 'ckoch', firstName: 'Clara', lastName: 'Koch', email: 'clara.koch@example.com', role: 'user', password: 'ckoch' },
  { id: '21', username: 'mschaefer', firstName: 'Markus', lastName: 'Schäfer', email: 'markus.schaefer@example.com', role: 'user', password: 'mschaefer' },
  { id: '22', username: 'hfriedrich', firstName: 'Hannah', lastName: 'Friedrich', email: 'hannah.friedrich@example.com', role: 'user', password: 'hfriedrich' },
  { id: '23', username: 'alegner', firstName: 'Alexander', lastName: 'Legner', email: 'alexander.legner@example.com', role: 'admin', password: 'alegner' },
  { id: '24', username: 'eberger', firstName: 'Eva', lastName: 'Berger', email: 'eva.berger@example.com', role: 'user', password: 'eberger' },
  { id: '25', username: 'rwinkler', firstName: 'Robert', lastName: 'Winkler', email: 'robert.winkler@example.com', role: 'user', password: 'rwinkler' },
  { id: '26', username: 'themmerich', firstName: 'Tobias', lastName: 'Hemmerich', email: 'tobias.hemmerich@example.com', role: 'user', password: 'themmerich' },
  { id: '27', username: 'svogt', firstName: 'Sandra', lastName: 'Vogt', email: 'sandra.vogt@example.com', role: 'user', password: 'svogt' },
  { id: '28', username: 'mstein', firstName: 'Marco', lastName: 'Stein', email: 'marco.stein@example.com', role: 'user', password: 'mstein' },
  { id: '29', username: 'jlang', firstName: 'Jana', lastName: 'Lang', email: 'jana.lang@example.com', role: 'user', password: 'jlang' },
  { id: '30', username: 'pmaier', firstName: 'Patrick', lastName: 'Maier', email: 'patrick.maier@example.com', role: 'user', password: 'pmaier' },
  {
    id: '31', username: 'hemm', firstName: 'Thomas', lastName: 'Hemmerich', email: 'thomas.hemmerich@example.com', role: 'user', password: 'hemm',
    birthDate: '1977-10-06', heightCm: 175,
    weightHistory: [
      { date: '2026-03-01', weightKg: 83.5 },
      { date: '2026-03-03', weightKg: 83.2 },
      { date: '2026-03-05', weightKg: 82.9 },
      { date: '2026-03-07', weightKg: 82.5 },
      { date: '2026-03-09', weightKg: 82.1 },
      { date: '2026-03-10', weightKg: 81.8 },
      { date: '2026-03-12', weightKg: 81.4 },
      { date: '2026-03-14', weightKg: 81.0 },
      { date: '2026-03-15', weightKg: 80.7 },
      { date: '2026-03-17', weightKg: 80.3 },
      { date: '2026-03-18', weightKg: 80.0 },
      { date: '2026-03-20', weightKg: 79.6 },
      { date: '2026-03-22', weightKg: 79.2 },
      { date: '2026-03-23', weightKg: 78.9 },
      { date: '2026-03-25', weightKg: 78.5 },
      { date: '2026-03-26', weightKg: 78.1 },
      { date: '2026-03-27', weightKg: 77.8 },
      { date: '2026-03-28', weightKg: 77.5 },
      { date: '2026-03-30', weightKg: 77.25 },
    ],
  },
];
