import { UserProfile } from '../model/user.model';

export const MOCK_USERS: UserProfile[] = [
  { id: '1', username: 'admin', displayName: 'Max Mustermann', email: 'max@example.com', role: 'admin', password: 'admin' },
  { id: '2', username: 'jdoe', displayName: 'Jane Doe', email: 'jane@example.com', role: 'user' },
  { id: '3', username: 'bsmith', displayName: 'Bob Smith', email: 'bob@example.com', role: 'user' },
  { id: '4', username: 'amueller', displayName: 'Anna Müller', email: 'anna.mueller@example.com', role: 'user' },
  { id: '5', username: 'tweber', displayName: 'Thomas Weber', email: 'thomas.weber@example.com', role: 'user' },
  { id: '6', username: 'lschneider', displayName: 'Laura Schneider', email: 'laura.schneider@example.com', role: 'admin', password: 'lschneider' },
  { id: '7', username: 'mfischer', displayName: 'Michael Fischer', email: 'michael.fischer@example.com', role: 'user' },
  { id: '8', username: 'swagner', displayName: 'Sophie Wagner', email: 'sophie.wagner@example.com', role: 'user' },
  { id: '9', username: 'phoffmann', displayName: 'Paul Hoffmann', email: 'paul.hoffmann@example.com', role: 'user' },
  { id: '10', username: 'kbauer', displayName: 'Katrin Bauer', email: 'katrin.bauer@example.com', role: 'user' },
  { id: '11', username: 'jrichter', displayName: 'Jonas Richter', email: 'jonas.richter@example.com', role: 'admin', password: 'jrichter' },
  { id: '12', username: 'mklein', displayName: 'Maria Klein', email: 'maria.klein@example.com', role: 'user' },
  { id: '13', username: 'dschmidt', displayName: 'Daniel Schmidt', email: 'daniel.schmidt@example.com', role: 'user' },
  { id: '14', username: 'lbraun', displayName: 'Lisa Braun', email: 'lisa.braun@example.com', role: 'user' },
  { id: '15', username: 'fkrause', displayName: 'Felix Krause', email: 'felix.krause@example.com', role: 'user' },
  { id: '16', username: 'nwolf', displayName: 'Nina Wolf', email: 'nina.wolf@example.com', role: 'admin', password: 'nwolf' },
  { id: '17', username: 'sschulz', displayName: 'Stefan Schulz', email: 'stefan.schulz@example.com', role: 'user' },
  { id: '18', username: 'jneumann', displayName: 'Julia Neumann', email: 'julia.neumann@example.com', role: 'user' },
  { id: '19', username: 'thaas', displayName: 'Tim Haas', email: 'tim.haas@example.com', role: 'user' },
  { id: '20', username: 'ckoch', displayName: 'Clara Koch', email: 'clara.koch@example.com', role: 'user' },
  { id: '21', username: 'mschaefer', displayName: 'Markus Schäfer', email: 'markus.schaefer@example.com', role: 'user' },
  { id: '22', username: 'hfriedrich', displayName: 'Hannah Friedrich', email: 'hannah.friedrich@example.com', role: 'user' },
  { id: '23', username: 'alegner', displayName: 'Alexander Legner', email: 'alexander.legner@example.com', role: 'admin', password: 'alegner' },
  { id: '24', username: 'eberger', displayName: 'Eva Berger', email: 'eva.berger@example.com', role: 'user' },
  { id: '25', username: 'rwinkler', displayName: 'Robert Winkler', email: 'robert.winkler@example.com', role: 'user' },
  { id: '26', username: 'themmerich', displayName: 'Tobias Hemmerich', email: 'tobias.hemmerich@example.com', role: 'user' },
  { id: '27', username: 'svogt', displayName: 'Sandra Vogt', email: 'sandra.vogt@example.com', role: 'user' },
  { id: '28', username: 'mstein', displayName: 'Marco Stein', email: 'marco.stein@example.com', role: 'user' },
  { id: '29', username: 'jlang', displayName: 'Jana Lang', email: 'jana.lang@example.com', role: 'user' },
  { id: '30', username: 'pmaier', displayName: 'Patrick Maier', email: 'patrick.maier@example.com', role: 'user' },
  {
    id: '31', username: 'hemm', displayName: 'Thomas Hemmerich', email: 'thomas.hemmerich@example.com', role: 'user',
    birthDate: '1977-10-06', heightCm: 175,
    weightHistory: [
      { date: '2026-03-01', weightKg: 83.5 },
      { date: '2026-03-03', weightKg: 83.2 },
      { date: '2026-03-05', weightKg: 82.9 },
      { date: '2026-03-07', weightKg: 82.5 },
      { date: '2026-03-09', weightKg: 82.1 },
      { date: '2026-03-10', weightKg: 81.8 },
      { date: '2026-03-12', weightKg: 81.4 },
      { date: '2026-03-14', weightKg: 81.0 },
      { date: '2026-03-15', weightKg: 80.7 },
      { date: '2026-03-17', weightKg: 80.3 },
      { date: '2026-03-18', weightKg: 80.0 },
      { date: '2026-03-20', weightKg: 79.6 },
      { date: '2026-03-22', weightKg: 79.2 },
      { date: '2026-03-23', weightKg: 78.9 },
      { date: '2026-03-25', weightKg: 78.5 },
      { date: '2026-03-26', weightKg: 78.1 },
      { date: '2026-03-27', weightKg: 77.8 },
      { date: '2026-03-28', weightKg: 77.5 },
      { date: '2026-03-30', weightKg: 77.25 },
    ],
  },
];
