import { UserProfile } from '../model/user.model';

export const MOCK_USERS: UserProfile[] = [
  { id: '1', username: 'admin', displayName: 'Max Mustermann', email: 'max@example.com', role: 'admin', password: 'admin' },
  { id: '2', username: 'jdoe', displayName: 'Jane Doe', email: 'jane@example.com', role: 'user' },
  { id: '3', username: 'bsmith', displayName: 'Bob Smith', email: 'bob@example.com', role: 'user' },
  { id: '4', username: 'amueller', displayName: 'Anna Müller', email: 'anna.mueller@example.com', role: 'user' },
  { id: '5', username: 'tweber', displayName: 'Thomas Weber', email: 'thomas.weber@example.com', role: 'user' },
  { id: '6', username: 'lschneider', displayName: 'Laura Schneider', email: 'laura.schneider@example.com', role: 'admin', password: 'lschneider' },
  { id: '7', username: 'mfischer', displayName: 'Michael Fischer', email: 'michael.fischer@example.com', role: 'user' },
  { id: '8', username: 'swagner', displayName: 'Sophie Wagner', email: 'sophie.wagner@example.com', role: 'user' },
  { id: '9', username: 'phoffmann', displayName: 'Paul Hoffmann', email: 'paul.hoffmann@example.com', role: 'user' },
  { id: '10', username: 'kbauer', displayName: 'Katrin Bauer', email: 'katrin.bauer@example.com', role: 'user' },
  { id: '11', username: 'jrichter', displayName: 'Jonas Richter', email: 'jonas.richter@example.com', role: 'admin', password: 'jrichter' },
  { id: '12', username: 'mklein', displayName: 'Maria Klein', email: 'maria.klein@example.com', role: 'user' },
  { id: '13', username: 'dschmidt', displayName: 'Daniel Schmidt', email: 'daniel.schmidt@example.com', role: 'user' },
  { id: '14', username: 'lbraun', displayName: 'Lisa Braun', email: 'lisa.braun@example.com', role: 'user' },
  { id: '15', username: 'fkrause', displayName: 'Felix Krause', email: 'felix.krause@example.com', role: 'user' },
  { id: '16', username: 'nwolf', displayName: 'Nina Wolf', email: 'nina.wolf@example.com', role: 'admin', password: 'nwolf' },
  { id: '17', username: 'sschulz', displayName: 'Stefan Schulz', email: 'stefan.schulz@example.com', role: 'user' },
  { id: '18', username: 'jneumann', displayName: 'Julia Neumann', email: 'julia.neumann@example.com', role: 'user' },
  { id: '19', username: 'thaas', displayName: 'Tim Haas', email: 'tim.haas@example.com', role: 'user' },
  { id: '20', username: 'ckoch', displayName: 'Clara Koch', email: 'clara.koch@example.com', role: 'user' },
  { id: '21', username: 'mschaefer', displayName: 'Markus Schäfer', email: 'markus.schaefer@example.com', role: 'user' },
  { id: '22', username: 'hfriedrich', displayName: 'Hannah Friedrich', email: 'hannah.friedrich@example.com', role: 'user' },
  { id: '23', username: 'alegner', displayName: 'Alexander Legner', email: 'alexander.legner@example.com', role: 'admin', password: 'alegner' },
  { id: '24', username: 'eberger', displayName: 'Eva Berger', email: 'eva.berger@example.com', role: 'user' },
  { id: '25', username: 'rwinkler', displayName: 'Robert Winkler', email: 'robert.winkler@example.com', role: 'user' },
];
